//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupStats.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCupStats.WPF.Resources.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a team first..
        /// </summary>
        public static string MainView_NoTeamSelected_Message {
            get {
                return ResourceManager.GetString("MainView_NoTeamSelected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Team Selected.
        /// </summary>
        public static string MainView_NoTeamSelected_Title {
            get {
                return ResourceManager.GetString("MainView_NoTeamSelected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainView_Settings_Tooltip {
            get {
                return ResourceManager.GetString("MainView_Settings_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Cup Stats.
        /// </summary>
        public static string MainView_Title {
            get {
                return ResourceManager.GetString("MainView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain:.
        /// </summary>
        public static string PlayerInfo_Captain {
            get {
                return ResourceManager.GetString("PlayerInfo_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals:.
        /// </summary>
        public static string PlayerInfo_Goals {
            get {
                return ResourceManager.GetString("PlayerInfo_Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        public static string PlayerInfo_Number {
            get {
                return ResourceManager.GetString("PlayerInfo_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string PlayerInfo_Position {
            get {
                return ResourceManager.GetString("PlayerInfo_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Information.
        /// </summary>
        public static string PlayerInfo_Title {
            get {
                return ResourceManager.GetString("PlayerInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Cards:.
        /// </summary>
        public static string PlayerInfo_YellowCards {
            get {
                return ResourceManager.GetString("PlayerInfo_YellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Settings_Cancel {
            get {
                return ResourceManager.GetString("Settings_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Championship.
        /// </summary>
        public static string Settings_Championship {
            get {
                return ResourceManager.GetString("Settings_Championship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save these settings?.
        /// </summary>
        public static string Settings_ConfirmSave {
            get {
                return ResourceManager.GetString("Settings_ConfirmSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Settings.
        /// </summary>
        public static string Settings_ConfirmTitle {
            get {
                return ResourceManager.GetString("Settings_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski.
        /// </summary>
        public static string Settings_Croatian {
            get {
                return ResourceManager.GetString("Settings_Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        public static string Settings_DisplayMode {
            get {
                return ResourceManager.GetString("Settings_DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Settings_English {
            get {
                return ResourceManager.GetString("Settings_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string Settings_Fullscreen {
            get {
                return ResourceManager.GetString("Settings_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large (1200x800).
        /// </summary>
        public static string Settings_LargeSize {
            get {
                return ResourceManager.GetString("Settings_LargeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium (1000x700).
        /// </summary>
        public static string Settings_MediumSize {
            get {
                return ResourceManager.GetString("Settings_MediumSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string Settings_Men {
            get {
                return ResourceManager.GetString("Settings_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small (800x600).
        /// </summary>
        public static string Settings_SmallSize {
            get {
                return ResourceManager.GetString("Settings_SmallSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        public static string Settings_Windowed {
            get {
                return ResourceManager.GetString("Settings_Windowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string Settings_Women {
            get {
                return ResourceManager.GetString("Settings_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws:.
        /// </summary>
        public static string TeamInfo_Draws {
            get {
                return ResourceManager.GetString("TeamInfo_Draws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA Code: {0}.
        /// </summary>
        public static string TeamInfo_FifaCode {
            get {
                return ResourceManager.GetString("TeamInfo_FifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Played:.
        /// </summary>
        public static string TeamInfo_GamesPlayed {
            get {
                return ResourceManager.GetString("TeamInfo_GamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Difference:.
        /// </summary>
        public static string TeamInfo_GoalDifference {
            get {
                return ResourceManager.GetString("TeamInfo_GoalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals Conceded:.
        /// </summary>
        public static string TeamInfo_GoalsConceded {
            get {
                return ResourceManager.GetString("TeamInfo_GoalsConceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals Scored:.
        /// </summary>
        public static string TeamInfo_GoalsScored {
            get {
                return ResourceManager.GetString("TeamInfo_GoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses:.
        /// </summary>
        public static string TeamInfo_Losses {
            get {
                return ResourceManager.GetString("TeamInfo_Losses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Information.
        /// </summary>
        public static string TeamInfo_Title {
            get {
                return ResourceManager.GetString("TeamInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins:.
        /// </summary>
        public static string TeamInfo_Wins {
            get {
                return ResourceManager.GetString("TeamInfo_Wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
